/**
 * adapters/dummy/bunker/seedBunkerNodes.ts
 * 
 * Deterministic BunkerNode seed data derived from existing SEED_PORTS.
 * No randomness. All values are hard-coded with professional realism.
 */

import { BunkerNode, Availability, CIGrade, ConfidenceLabel, FuelProduct } from '../../../domain/bunker/types';
import { Region } from '../../../domain/constants';

// ---------------------------------------------------------------------------
// Helpers — keep pure and deterministic
// ---------------------------------------------------------------------------

function deriveLabel(score: number): ConfidenceLabel {
    if (score >= 75) return 'high';
    if (score >= 45) return 'medium';
    return 'low';
}

type AvailabilityMap = Record<FuelProduct, Availability>;

function avail(
    eMeth: Availability,
    eAmm: Availability,
    vlsfo: Availability,
    mgo: Availability,
    other: Availability = 'unknown',
): AvailabilityMap {
    return { e_methanol: eMeth, e_ammonia: eAmm, vlsfo, mgo, other };
}

type CIMap = Partial<Record<FuelProduct, CIGrade>>;

function ci(eMeth?: CIGrade, eAmm?: CIGrade): CIMap {
    const map: CIMap = {};
    if (eMeth) map.e_methanol = eMeth;
    if (eAmm) map.e_ammonia = eAmm;
    return map;
}

// ---------------------------------------------------------------------------
// Seed data — 46 nodes matching existing SEED_PORTS locodes
// ---------------------------------------------------------------------------

export const SEED_BUNKER_NODES: BunkerNode[] = [
    // ── North Europe ─────────────────────────────────────────────────────────
    {
        locode: 'NLRTM',
        portName: 'Rotterdam',
        region: 'north_europe' as Region,
        lat: 51.95, lon: 4.14,
        availability: avail('available', 'available', 'available', 'available', 'available'),
        confidenceScore: 92,
        confidenceLabel: deriveLabel(92),
        ciGrade: ci('A', 'B'),
        lastUpdated: '2026-02-01T00:00:00Z',
    },
    {
        locode: 'BEANR',
        portName: 'Antwerp',
        region: 'north_europe' as Region,
        lat: 51.21, lon: 4.40,
        availability: avail('available', 'limited', 'available', 'available', 'limited'),
        confidenceScore: 85,
        confidenceLabel: deriveLabel(85),
        ciGrade: ci('A', 'C'),
        lastUpdated: '2026-02-01T00:00:00Z',
    },
    {
        locode: 'DEHAM',
        portName: 'Hamburg',
        region: 'north_europe' as Region,
        lat: 53.54, lon: 9.99,
        availability: avail('available', 'limited', 'available', 'available', 'unknown'),
        confidenceScore: 88,
        confidenceLabel: deriveLabel(88),
        ciGrade: ci('B', 'C'),
        lastUpdated: '2026-02-01T00:00:00Z',
    },
    {
        locode: 'DEBRV',
        portName: 'Bremerhaven',
        region: 'north_europe' as Region,
        lat: 53.54, lon: 8.58,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 70,
        confidenceLabel: deriveLabel(70),
        ciGrade: ci('B', 'unknown'),
        lastUpdated: '2026-01-15T00:00:00Z',
    },
    {
        locode: 'GBFXT',
        portName: 'Felixstowe',
        region: 'north_europe' as Region,
        lat: 51.96, lon: 1.35,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 55,
        confidenceLabel: deriveLabel(55),
        ciGrade: ci('C', 'unknown'),
        lastUpdated: '2026-01-10T00:00:00Z',
    },
    {
        locode: 'SEGOT',
        portName: 'Gothenburg',
        region: 'north_europe' as Region,
        lat: 57.71, lon: 11.97,
        availability: avail('available', 'limited', 'available', 'available', 'unknown'),
        confidenceScore: 78,
        confidenceLabel: deriveLabel(78),
        ciGrade: ci('A', 'B'),
        lastUpdated: '2026-02-01T00:00:00Z',
    },
    {
        locode: 'NLAMS',
        portName: 'Amsterdam',
        region: 'north_europe' as Region,
        lat: 52.37, lon: 4.90,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 68,
        confidenceLabel: deriveLabel(68),
        ciGrade: ci('B', 'unknown'),
        lastUpdated: '2026-01-20T00:00:00Z',
    },

    // ── Mediterranean ─────────────────────────────────────────────────────────
    {
        locode: 'GIGIB',
        portName: 'Gibraltar',
        region: 'mediterranean' as Region,
        lat: 36.14, lon: -5.35,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 62,
        confidenceLabel: deriveLabel(62),
        ciGrade: ci('C', 'unknown'),
        lastUpdated: '2026-01-25T00:00:00Z',
    },
    {
        locode: 'ESBCN',
        portName: 'Barcelona',
        region: 'mediterranean' as Region,
        lat: 41.38, lon: 2.17,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 72,
        confidenceLabel: deriveLabel(72),
        ciGrade: ci('B', 'unknown'),
        lastUpdated: '2026-02-01T00:00:00Z',
    },
    {
        locode: 'ITGOA',
        portName: 'Genoa',
        region: 'mediterranean' as Region,
        lat: 44.41, lon: 8.93,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 55,
        confidenceLabel: deriveLabel(55),
        ciGrade: ci('C', 'unknown'),
        lastUpdated: '2026-01-10T00:00:00Z',
    },
    {
        locode: 'GRPIR',
        portName: 'Piraeus',
        region: 'mediterranean' as Region,
        lat: 37.94, lon: 23.65,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 50,
        confidenceLabel: deriveLabel(50),
        ciGrade: ci('D', 'unknown'),
        lastUpdated: '2026-01-05T00:00:00Z',
    },
    {
        locode: 'ESVLC',
        portName: 'Valencia',
        region: 'mediterranean' as Region,
        lat: 39.47, lon: -0.38,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 48,
        confidenceLabel: deriveLabel(48),
        ciGrade: ci('D', 'unknown'),
        lastUpdated: '2026-01-01T00:00:00Z',
    },
    {
        locode: 'FRMRS',
        portName: 'Marseille',
        region: 'mediterranean' as Region,
        lat: 43.30, lon: 5.37,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 65,
        confidenceLabel: deriveLabel(65),
        ciGrade: ci('C', 'unknown'),
        lastUpdated: '2026-01-20T00:00:00Z',
    },
    {
        locode: 'TRIST',
        portName: 'Istanbul',
        region: 'mediterranean' as Region,
        lat: 41.02, lon: 28.97,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 42,
        confidenceLabel: deriveLabel(42),
        ciGrade: ci('E', 'unknown'),
        lastUpdated: '2025-12-15T00:00:00Z',
    },

    // ── Middle East ──────────────────────────────────────────────────────────
    {
        locode: 'AEFJR',
        portName: 'Fujairah',
        region: 'middle_east' as Region,
        lat: 25.12, lon: 56.32,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 80,
        confidenceLabel: deriveLabel(80),
        ciGrade: ci('B', 'D'),
        lastUpdated: '2026-02-01T00:00:00Z',
    },
    {
        locode: 'AEJEA',
        portName: 'Jebel Ali',
        region: 'middle_east' as Region,
        lat: 25.01, lon: 55.03,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 76,
        confidenceLabel: deriveLabel(76),
        ciGrade: ci('B', 'D'),
        lastUpdated: '2026-02-01T00:00:00Z',
    },
    {
        locode: 'SAJED',
        portName: 'Jeddah',
        region: 'middle_east' as Region,
        lat: 21.54, lon: 39.17,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 52,
        confidenceLabel: deriveLabel(52),
        ciGrade: ci('D', 'unknown'),
        lastUpdated: '2026-01-05T00:00:00Z',
    },
    {
        locode: 'AEKHF',
        portName: 'Khor Fakkan',
        region: 'middle_east' as Region,
        lat: 25.33, lon: 56.35,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 40,
        confidenceLabel: deriveLabel(40),
        ciGrade: ci('unknown', 'unknown'),
        lastUpdated: '2025-12-01T00:00:00Z',
    },
    {
        locode: 'OMSOH',
        portName: 'Sohar',
        region: 'middle_east' as Region,
        lat: 24.36, lon: 56.75,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 45,
        confidenceLabel: deriveLabel(45),
        ciGrade: ci('D', 'unknown'),
        lastUpdated: '2025-12-15T00:00:00Z',
    },

    // ── Asia ─────────────────────────────────────────────────────────────────
    {
        locode: 'SGSIN',
        portName: 'Singapore',
        region: 'asia' as Region,
        lat: 1.35, lon: 103.81,
        availability: avail('available', 'available', 'available', 'available', 'available'),
        confidenceScore: 95,
        confidenceLabel: deriveLabel(95),
        ciGrade: ci('A', 'A'),
        lastUpdated: '2026-02-01T00:00:00Z',
    },
    {
        locode: 'CNSHA',
        portName: 'Shanghai',
        region: 'asia' as Region,
        lat: 31.23, lon: 121.47,
        availability: avail('available', 'limited', 'available', 'available', 'unknown'),
        confidenceScore: 88,
        confidenceLabel: deriveLabel(88),
        ciGrade: ci('B', 'C'),
        lastUpdated: '2026-02-01T00:00:00Z',
    },
    {
        locode: 'KRPUS',
        portName: 'Busan',
        region: 'asia' as Region,
        lat: 35.17, lon: 129.07,
        availability: avail('limited', 'limited', 'available', 'available', 'unknown'),
        confidenceScore: 75,
        confidenceLabel: deriveLabel(75),
        ciGrade: ci('B', 'C'),
        lastUpdated: '2026-01-25T00:00:00Z',
    },
    {
        locode: 'HKHKG',
        portName: 'Hong Kong',
        region: 'asia' as Region,
        lat: 22.32, lon: 114.17,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 70,
        confidenceLabel: deriveLabel(70),
        ciGrade: ci('B', 'unknown'),
        lastUpdated: '2026-01-20T00:00:00Z',
    },
    {
        locode: 'JPTYO',
        portName: 'Tokyo',
        region: 'asia' as Region,
        lat: 35.65, lon: 139.84,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 72,
        confidenceLabel: deriveLabel(72),
        ciGrade: ci('B', 'unknown'),
        lastUpdated: '2026-01-15T00:00:00Z',
    },
    {
        locode: 'JPYOK',
        portName: 'Yokohama',
        region: 'asia' as Region,
        lat: 35.44, lon: 139.64,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 68,
        confidenceLabel: deriveLabel(68),
        ciGrade: ci('B', 'unknown'),
        lastUpdated: '2026-01-10T00:00:00Z',
    },
    {
        locode: 'CNNGB',
        portName: 'Ningbo',
        region: 'asia' as Region,
        lat: 29.87, lon: 121.55,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 60,
        confidenceLabel: deriveLabel(60),
        ciGrade: ci('C', 'unknown'),
        lastUpdated: '2026-01-05T00:00:00Z',
    },
    {
        locode: 'CNSZX',
        portName: 'Shenzhen',
        region: 'asia' as Region,
        lat: 22.54, lon: 114.06,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 58,
        confidenceLabel: deriveLabel(58),
        ciGrade: ci('C', 'unknown'),
        lastUpdated: '2026-01-05T00:00:00Z',
    },
    {
        locode: 'MYPKG',
        portName: 'Klang',
        region: 'asia' as Region,
        lat: 3.00, lon: 101.39,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 65,
        confidenceLabel: deriveLabel(65),
        ciGrade: ci('C', 'unknown'),
        lastUpdated: '2026-01-15T00:00:00Z',
    },

    // ── North America ─────────────────────────────────────────────────────────
    {
        locode: 'USNYC',
        portName: 'New York',
        region: 'north_america' as Region,
        lat: 40.71, lon: -74.00,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 74,
        confidenceLabel: deriveLabel(74),
        ciGrade: ci('C', 'unknown'),
        lastUpdated: '2026-01-25T00:00:00Z',
    },
    {
        locode: 'USHOU',
        portName: 'Houston',
        region: 'north_america' as Region,
        lat: 29.76, lon: -95.36,
        availability: avail('available', 'limited', 'available', 'available', 'unknown'),
        confidenceScore: 82,
        confidenceLabel: deriveLabel(82),
        ciGrade: ci('B', 'C'),
        lastUpdated: '2026-02-01T00:00:00Z',
    },
    {
        locode: 'USLAX',
        portName: 'Los Angeles',
        region: 'north_america' as Region,
        lat: 33.74, lon: -118.27,
        availability: avail('available', 'limited', 'available', 'available', 'unknown'),
        confidenceScore: 80,
        confidenceLabel: deriveLabel(80),
        ciGrade: ci('A', 'B'),
        lastUpdated: '2026-02-01T00:00:00Z',
    },
    {
        locode: 'USOAK',
        portName: 'Oakland',
        region: 'north_america' as Region,
        lat: 37.80, lon: -122.27,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 65,
        confidenceLabel: deriveLabel(65),
        ciGrade: ci('B', 'unknown'),
        lastUpdated: '2026-01-20T00:00:00Z',
    },
    {
        locode: 'CAVAN',
        portName: 'Vancouver',
        region: 'north_america' as Region,
        lat: 49.28, lon: -123.12,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 68,
        confidenceLabel: deriveLabel(68),
        ciGrade: ci('B', 'unknown'),
        lastUpdated: '2026-01-15T00:00:00Z',
    },
    {
        locode: 'USSEA',
        portName: 'Seattle',
        region: 'north_america' as Region,
        lat: 47.61, lon: -122.33,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 62,
        confidenceLabel: deriveLabel(62),
        ciGrade: ci('B', 'unknown'),
        lastUpdated: '2026-01-10T00:00:00Z',
    },
    {
        locode: 'CAMTR',
        portName: 'Montreal',
        region: 'north_america' as Region,
        lat: 45.50, lon: -73.57,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 50,
        confidenceLabel: deriveLabel(50),
        ciGrade: ci('C', 'unknown'),
        lastUpdated: '2026-01-01T00:00:00Z',
    },

    // ── South America ─────────────────────────────────────────────────────────
    {
        locode: 'BRSSZ',
        portName: 'Santos',
        region: 'south_america' as Region,
        lat: -23.96, lon: -46.33,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 48,
        confidenceLabel: deriveLabel(48),
        ciGrade: ci('D', 'unknown'),
        lastUpdated: '2025-12-20T00:00:00Z',
    },
    {
        locode: 'ARBUE',
        portName: 'Buenos Aires',
        region: 'south_america' as Region,
        lat: -34.60, lon: -58.38,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 40,
        confidenceLabel: deriveLabel(40),
        ciGrade: ci('unknown', 'unknown'),
        lastUpdated: '2025-12-01T00:00:00Z',
    },
    {
        locode: 'PECLL',
        portName: 'Callao',
        region: 'south_america' as Region,
        lat: -12.05, lon: -77.15,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 35,
        confidenceLabel: deriveLabel(35),
        ciGrade: ci('unknown', 'unknown'),
        lastUpdated: '2025-11-15T00:00:00Z',
    },
    {
        locode: 'COCTG',
        portName: 'Cartagena',
        region: 'south_america' as Region,
        lat: 10.39, lon: -75.51,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 38,
        confidenceLabel: deriveLabel(38),
        ciGrade: ci('unknown', 'unknown'),
        lastUpdated: '2025-11-15T00:00:00Z',
    },

    // ── Africa ────────────────────────────────────────────────────────────────
    {
        locode: 'ZADUR',
        portName: 'Durban',
        region: 'africa' as Region,
        lat: -29.86, lon: 31.03,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 44,
        confidenceLabel: deriveLabel(44),
        ciGrade: ci('E', 'unknown'),
        lastUpdated: '2025-12-10T00:00:00Z',
    },
    {
        locode: 'NGLOS',
        portName: 'Lagos',
        region: 'africa' as Region,
        lat: 6.45, lon: 3.40,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 30,
        confidenceLabel: deriveLabel(30),
        ciGrade: ci('unknown', 'unknown'),
        lastUpdated: '2025-11-01T00:00:00Z',
    },
    {
        locode: 'KEMBA',
        portName: 'Mombasa',
        region: 'africa' as Region,
        lat: -4.05, lon: 39.67,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 32,
        confidenceLabel: deriveLabel(32),
        ciGrade: ci('unknown', 'unknown'),
        lastUpdated: '2025-11-01T00:00:00Z',
    },
    {
        locode: 'MAPTM',
        portName: 'Tangier',
        region: 'africa' as Region,
        lat: 35.77, lon: -5.81,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 42,
        confidenceLabel: deriveLabel(42),
        ciGrade: ci('E', 'unknown'),
        lastUpdated: '2025-12-01T00:00:00Z',
    },

    // ── Oceania ───────────────────────────────────────────────────────────────
    {
        locode: 'AUSYD',
        portName: 'Sydney',
        region: 'oceania' as Region,
        lat: -33.87, lon: 151.21,
        availability: avail('limited', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 66,
        confidenceLabel: deriveLabel(66),
        ciGrade: ci('C', 'unknown'),
        lastUpdated: '2026-01-15T00:00:00Z',
    },
    {
        locode: 'AUMEL',
        portName: 'Melbourne',
        region: 'oceania' as Region,
        lat: -37.81, lon: 144.96,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 55,
        confidenceLabel: deriveLabel(55),
        ciGrade: ci('C', 'unknown'),
        lastUpdated: '2026-01-05T00:00:00Z',
    },
    {
        locode: 'NZAKL',
        portName: 'Auckland',
        region: 'oceania' as Region,
        lat: -36.85, lon: 174.76,
        availability: avail('planned', 'planned', 'available', 'available', 'unknown'),
        confidenceScore: 48,
        confidenceLabel: deriveLabel(48),
        ciGrade: ci('D', 'unknown'),
        lastUpdated: '2025-12-15T00:00:00Z',
    },
];
